# Generated by Django 4.0.4 on 2022-05-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
