# Generated by Django 4.0.4 on 2022-05-27 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_options_alter_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
