# Generated by Django 4.0.4 on 2022-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.BigIntegerField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
