# Generated by Django 4.0.4 on 2022-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_bookinstance_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank='True', null=True, verbose_name='died'),
        ),
    ]
